"""Duplo - Duplicate any app by pointing at its website."""

# Eager submodule imports so attribute-style access (``duplo.main.X``,
# ``duplo.pipeline.Y``, etc.) resolves deterministically under
# ``--import-mode=importlib`` with pytest-xdist. Without these,
# `monkeypatch.setattr("duplo.main._check_migration", ...)` and similar
# patch sites race against worker import state and intermittently raise
# AttributeError.
from . import (
    _bs4_helpers,
    appshot,
    build_prefs,
    canonical_consistency,
    claude_cli,
    collector,
    comparator,
    council,
    design_extractor,
    diagnostics,
    doc_examples,
    doc_tables,
    docs_extractor,
    extractor,
    fetcher,
    frame_describer,
    frame_filter,
    gap_detector,
    hasher,
    init,
    investigator,
    issuer,
    main,
    migration,
    notifier,
    orchestrator,
    parsing,
    pdf_extractor,
    pipeline,
    planner,
    platforms,
    questioner,
    reauthor,
    reauthor_assemble,
    reauthor_phase_ids,
    roadmap,
    saver,
    scanner,
    schema_classification,
    screenshotter,
    selector,
    spec_reader,
    spec_writer,
    status,
    task_matcher,
    url_canon,
    validator,
    verification_extractor,
    video_extractor,
)
