"""Backward-compatible re-export shim for ``bob_tools.planfile.operations``.

Implementation has been split into focused sibling modules:
``_shared``, ``iteration``, ``construction``, ``validation``,
``semantic_diff``, ``canonical``, ``scheduling``, ``status``,
``task_addition``, ``migration``. Every name previously importable from
``bob_tools.planfile.operations`` continues to work via this shim. New code
should import from the focused modules directly.
"""

from __future__ import annotations

from bob_tools.planfile._shared import (
    _ACTION_NAME_RE,
    _ANNOTATION_KEY_ONLY_RE,
    _ANNOTATION_KEY_RE,
    _ANNOTATION_OK_RE,
    _INCOMPLETE_CHECKBOX_RE,
    _KNOWN_LEADING_FLAGS,
    _LEADING_TAG_LIKE_RE,
    _PHASE_ID_RE,
    _POSITIONAL_LABEL_RE,
    _RESERVED_SIBLING_MARKERS,
    _TASK_ID_NUMERIC_RE,
    _TASK_REF_RE,
    _TRAILING_BRACKET_RE,
    _contains_newline,
    _now_iso_utc,
    _task_path_label,
    _task_ref,
)
from bob_tools.planfile.canonical import (
    _count_todo_tasks,
    _phase_id_for_task_context,
    _resolve_positional_label,
    _task_matches_label,
    assert_mcloop_canonical,
    resolve_task_context,
)
from bob_tools.planfile.construction import (
    _apply_task_id_sentinels,
    _assert_task_field_stability,
    _compare_task_fields,
    _construction_sentinel_phase,
    _construction_sentinel_plan,
    _construction_sentinel_task,
    _explicit_task_ids,
    _field_value,
    _minimal_canonical_plan,
    _next_sentinel,
    _normalize_task_for_semantic_compare,
    _restore_sentinel_none_ids,
    _round_trip_scalar,
    _validate_scalar,
    _validate_task_for_construction,
    make_task,
)
from bob_tools.planfile.iteration import (
    _child_path_suffix,
    _find_task_by_id,
    _iter_phase_task_tree_with_label,
    _iter_phase_tasks_with_phase,
    _iter_plan_tasks,
    _iter_plan_tasks_with_label,
    _iter_plan_top_level_tasks_with_label,
    _iter_task_tree_with_paths,
    _iter_tasks,
    _plan_phase_path,
    _plan_subsection_path,
    bug_count,
)
from bob_tools.planfile.migration import (
    _assign_task_ids,
    _max_phase_id_number,
    _next_task_id_number,
    migrate,
    replace_phase,
    replace_phase_validated,
)
from bob_tools.planfile.parser import parse_plan
from bob_tools.planfile.renderer import render_plan
from bob_tools.planfile.scheduling import (
    _all_tasks_done,
    _build_done_ids,
    _deps_satisfied,
    _get_batch_children,
    _phase_complete,
    _walk_actionable,
    next_tasks,
)
from bob_tools.planfile.semantic_diff import (
    _collect_bugs_semantic_diff,
    _collect_phase_semantic_diff,
    _collect_plan_semantic_diff,
    _collect_subsection_semantic_diff,
    _collect_task_semantic_diff,
    _normalize_bugs_for_semantic_compare,
    _normalize_phase_for_semantic_compare,
    _normalize_plan_for_semantic_compare,
    _normalize_subsection_for_semantic_compare,
    _normalize_task_for_position,
)
from bob_tools.planfile.status import (
    _EVENT_TYPE_TO_EXPECTED_STATUS,
    _apply_status_to_plan,
    _apply_to_phase,
    _clear_failed_in_tasks,
    _direct_completion_kind,
    _event_task_id,
    _flip_in_tree,
    _LedgerEvent,
    _purge_done_tasks,
    _settlement_phase_id,
    check_consistency,
    clear_failed,
    complete_task,
    fail_task,
    purge_done_bug_tasks,
    reset_task,
)
from bob_tools.planfile.task_addition import (
    _bug_dedup_keys,
    _next_task_id,
    _normalize_bug_text,
    _try_add_under_parent,
    add_bug_task,
    add_phase_task,
    add_task,
)
from bob_tools.planfile.validation import (
    _check_constructed_invariants,
    _check_each_task_field_stability,
    _check_leading_bracket_tag,
    _check_non_task_scalar_field_stability,
    _check_trailing_annotation,
    validate_plan,
)

__all__ = [
    "_ACTION_NAME_RE",
    "_ANNOTATION_KEY_ONLY_RE",
    "_ANNOTATION_KEY_RE",
    "_ANNOTATION_OK_RE",
    "_EVENT_TYPE_TO_EXPECTED_STATUS",
    "_INCOMPLETE_CHECKBOX_RE",
    "_KNOWN_LEADING_FLAGS",
    "_LEADING_TAG_LIKE_RE",
    "_PHASE_ID_RE",
    "_POSITIONAL_LABEL_RE",
    "_RESERVED_SIBLING_MARKERS",
    "_TASK_ID_NUMERIC_RE",
    "_TASK_REF_RE",
    "_TRAILING_BRACKET_RE",
    "_LedgerEvent",
    "_all_tasks_done",
    "_apply_status_to_plan",
    "_apply_task_id_sentinels",
    "_apply_to_phase",
    "_assert_task_field_stability",
    "_assign_task_ids",
    "_bug_dedup_keys",
    "_build_done_ids",
    "_check_constructed_invariants",
    "_check_each_task_field_stability",
    "_check_leading_bracket_tag",
    "_check_non_task_scalar_field_stability",
    "_check_trailing_annotation",
    "_child_path_suffix",
    "_clear_failed_in_tasks",
    "_collect_bugs_semantic_diff",
    "_collect_phase_semantic_diff",
    "_collect_plan_semantic_diff",
    "_collect_subsection_semantic_diff",
    "_collect_task_semantic_diff",
    "_compare_task_fields",
    "_construction_sentinel_phase",
    "_construction_sentinel_plan",
    "_construction_sentinel_task",
    "_contains_newline",
    "_count_todo_tasks",
    "_deps_satisfied",
    "_direct_completion_kind",
    "_event_task_id",
    "_explicit_task_ids",
    "_field_value",
    "_find_task_by_id",
    "_flip_in_tree",
    "_get_batch_children",
    "_iter_phase_task_tree_with_label",
    "_iter_phase_tasks_with_phase",
    "_iter_plan_tasks",
    "_iter_plan_tasks_with_label",
    "_iter_plan_top_level_tasks_with_label",
    "_iter_task_tree_with_paths",
    "_iter_tasks",
    "_max_phase_id_number",
    "_minimal_canonical_plan",
    "_next_sentinel",
    "_next_task_id",
    "_next_task_id_number",
    "_normalize_bug_text",
    "_normalize_bugs_for_semantic_compare",
    "_normalize_phase_for_semantic_compare",
    "_normalize_plan_for_semantic_compare",
    "_normalize_subsection_for_semantic_compare",
    "_normalize_task_for_position",
    "_normalize_task_for_semantic_compare",
    "_now_iso_utc",
    "_phase_complete",
    "_phase_id_for_task_context",
    "_plan_phase_path",
    "_plan_subsection_path",
    "_purge_done_tasks",
    "_resolve_positional_label",
    "_restore_sentinel_none_ids",
    "_round_trip_scalar",
    "_settlement_phase_id",
    "_task_matches_label",
    "_task_path_label",
    "_task_ref",
    "_try_add_under_parent",
    "_validate_scalar",
    "_validate_task_for_construction",
    "_walk_actionable",
    "add_bug_task",
    "add_phase_task",
    "add_task",
    "assert_mcloop_canonical",
    "bug_count",
    "check_consistency",
    "clear_failed",
    "complete_task",
    "fail_task",
    "make_task",
    "migrate",
    "next_tasks",
    "parse_plan",
    "purge_done_bug_tasks",
    "render_plan",
    "replace_phase",
    "replace_phase_validated",
    "reset_task",
    "resolve_task_context",
    "validate_plan",
]
